# Generated by Django 5.0.6 on 2024-06-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to='objects_app.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='accessed_objects',
            field=models.ManyToManyField(related_name='accessors', to='objects_app.object'),
        ),
    ]
